### ISSUE TITLE
Gareb default captain on RIS Vo and Romulan Scout Vessel

### ISSUE THREAD

**Issue by mathguy6189** [spacedockapp/spacedock#180]
1.1.20 for Mac 
Gareb appears as the captain for both Romulan ships. He cannot be removed, and cannot be changed out.  If I select another captain, it simply adds them as the secondary captain for his ability.  

The bigger issue is that Gareb shouldn't even be allowed to go on the Scout Vessel (but I understand if you can't code that restriction) I'm just not sure why he's the default for only those two ships.  I checked every other Romulan ship, and none of them have that issue.

**Comment by rrgeorge** [comment]
This was caused by a missing generic captain for the RIS Vo set. This has been fixed, and you can simply update the data by choosing "Check for Updated Data" from the file menu.
