### ISSUE TITLE
Wishlist: Add option to ignore duplicate card issues

### ISSUE THREAD

**Issue by HeXetic** [spacedockapp/spacedock#182]
It would be nice if there were an option to ignore the duplicate-named-item rule when building squads. 

On the one hand, briefly ignoring this rule could make squad-building quicker from a user perspective. For example, if you put Mr. Spock on one ship, then realize as you are building the second ship that you **need** him on the second -- it would be faster to add him now, breaking the rules, then go and delete him from the other ship, rather than being forced to back out of the current ship's crew selection, go to the other ship, delete him from there, and then return to add him to the correct vessel.

On the other hand, sometimes people play for fun and like to bend or break some rules, while still making use of Space Dock to ensure they don't go over the points limit, or to quickly scan their collection. For example, some friends and I are planning to have a Spock-Must-Be-On-Every-Ship match in memory of Mr. Nemoy.

This feature would admittedly complicate the UI. Marking conflicting ships & broken squads with red text and highlighting conflicts in red is about the simplest way to do it, but there would still have to be an "option" somewhere to enable or disable breaking this rule.

**Comment by rrgeorge** [comment]
Sorry, this is not feasible.
