### ISSUE TITLE
Gul Madred (Admiral) - incorrect skill modifier

### ISSUE THREAD

**Issue by DrNicket** [spacedockapp/spacedock#185]
He is listed with a modifier of +0

Should be +2

**Comment by rrgeorge** [comment]
That's because the preview didn't show the Admiral side. Could you provide the Admiral side text as well?

**Comment by DrNicket** [comment]
Unique
Gul Madred
Admiral
"Fleet Action: Target a ship at Range 1-3. If the Captain on the target ship has a Skill number of 6 or less, discard that ship's Captain and Gul Madred. If the Captain on the target ship has a Skill number of 7 or higher, that Captain rolls 2 defense dice. If at least 1 [BS] result is rolled, do not discard that ship's Captain or Gul Madred."
CS +2
[ET]
Dominion
Cost: 5

**Comment by DrNicket** [comment]
Yeah, I recall that being the case. Darn legitimate reasoning.... Heheheh

**Comment by rrgeorge** [comment]
Thank you.
