### ISSUE TITLE
Enterprise NX-01 can't equip Enhanced Hull Plating natively

### ISSUE THREAD

**Issue by Urutsini** [spacedockapp/spacedock#192]
Enterprise NX-01 can't equip Enhanced Hull Plating natively. I can't see why anyone would not use the card so it might be easiest to have it added automatically. (Android)

**Comment by DrNicket** [comment]
if we can create a tech slot that can only equip the EHP (restricted), while still allowing Upgrade added Tech slots (like from T'Pol) to field anything compatible with the NX...

**Comment by Urutsini** [comment]
Failing adding extra programming to deal with it. How about adding the text for Hull Plating to the base NX ship ability?

**Comment by rrgeorge** [comment]
For iOS & Mac I do a bit of trickery here. First the Enhanced Hull Plating adds a Tech slot when equipped on the NX-01. Then, when the NX-01 is added to a fleet, the upgrade is automatically added to the ship. @tblackwe let me know if you need help getting this to work.

**Comment by tblackwe** [comment]
Robert and I share the same data, so adding text for just android isn't something I really want to do.

I'll research doing it the iOS way.

**Comment by rrgeorge** [comment]
9897f435b873fd99413abe4cd89f90825cc2093e
