### ISSUE TITLE
Enhancement request: Rename older OP "Expansions"

### ISSUE THREAD

**Issue by Urutsini** [spacedockapp/spacedock#197]
Any chance of the earlier OP event prizes/participation rewards renamed to what they actually represent, like they are listed nowadays? For example, rename the Expansion "Dominion War OP3 Competitive Prize" to "P.W.B. Aj'rmr". Maybe even include a reference to which OP event it was from, for example "P.W.B. Aj'rmr (Dom3 Comp Prize)". (Android)

**Comment by rrgeorge** [comment]
Done.
