### ISSUE TITLE
Sakharov ship ability not working

### ISSUE THREAD

**Issue by deltaangelfire** [spacedockapp/spacedock#202]
Entry for Sakharov does not include extra crew or tech slot mentioned in it's ship ability (extra crew or tech slot, that upgrade costs -2)

**Comment by DrNicket** [comment]
An easy fix might be to add special 'cards'. One called "Sakharov [Tech] Slot" and "Sakharov [Crew] Slot"  that can be equipped first and grants the slot it takes and the one it grants.

Same for NX-01 and the Hull plating.

**Comment by rrgeorge** [comment]
@DrNicket Thats exactly how I had planned to (and did) implement it on iOS & Mac.

**Comment by tblackwe** [comment]
I see 2 versions of the Sakharov in the data file, not special sakharov only cards. Did you change the way you implemented this or do I have an old version?

**Comment by rrgeorge** [comment]
One has an extra crew slot, and the other has an extra tech slot. They can't have different names because of uniqueness, so I display the title differently a la Jean-Luc Picard (8).

**Comment by Urutsini** [comment]
I noticed the Picard 8 thing a while ago. Any chance you could have the description only include the slot added for each version in the data file? Each time I go to add Picard 8, I have to choose each one until I get the right slot added. Same with Sakharov?

**Comment by DrNicket** [comment]
I wish to draw attention to Urutsini's last post again. 

Please make Picard 8 and Calvin Hudson function like this.

**Comment by Urutsini** [comment]
The Cargo Hold on Quark's Treasure has done exactly this :-)
