### ISSUE TITLE
Systems Upgrade does not add Tech slot

### ISSUE THREAD

**Issue by deltaangelfire** [spacedockapp/spacedock#204]
issue noticed on iphone. Systems Upgrade from the U.S.S. Hood prize ship is not adding its additional Tech slot

**Comment by rrgeorge** [comment]
This has been fixed on iOS & Mac

**Comment by deltaangelfire** [comment]
Just checked on data version 2015-05-31@20-38 on my iPhone, still seems to be an issue.

**Comment by rrgeorge** [comment]
It has been fixed, but requires a software update. The new version is waiting on Apple's approval.

**Comment by tblackwe** [comment]
Acknowledged.

This is a spot where supporting multiple specials would be helpful, but I haven't gotten to it.

**Comment by ODLStelco** [comment]
Still an issue in version 1.1.18(56) Android build

**Comment by DrNicket** [comment]
Fixed in Android.
