### ISSUE TITLE
Chroniton Torpedoes - Missing penalty for non-Krenim ship

### ISSUE THREAD

**Issue by DrNicket** [spacedockapp/spacedock#209]
I equipped the Chroniton Torpedoes out of faction and only received a +1 SP penalty. It requires another +6 SP.

**Comment by ketsue** [comment]
Also worth noting that this should be a ship penalty and not a faction penalty. This can't be used on a non Krenim ship.

**Comment by DrNicket** [comment]
Yes it can be used on non-Krenim ship. That is why the Ship penalty. (I'll assume there was a typo)
