### ISSUE TITLE
Type 8 Phaser Array can be equipped to a ship regardless of primary attack value.

### ISSUE THREAD

**Issue by ketsue** [spacedockapp/spacedock#211]
This card should only be applicable to ships with a primary weapon value of 3 or less.

**Comment by DrNicket** [comment]
Type 8 Phaser Array can still be illegally equipped to ships with higher PWV.

**Comment by rrgeorge** [comment]
What version?

**Comment by DrNicket** [comment]
iOS Data Version 2015-07-04-17@17-57

**Comment by rrgeorge** [comment]
iOS App is waiting for review.

**Comment by DrNicket** [comment]
Understood. Thank you for your patience with us, while we work on being patient with you (and Apple ;-)

**Comment by DrNicket** [comment]
Upgraded Phasers can also be assigned to a ship with PWV greater than 3 (ex. Ent-E)

**Comment by DrNicket** [comment]
Upgraded Phasers can still be equipped to a PWV 4+ ship - Perhaps a new Issue should be created... <walks over to new page>
