### ISSUE TITLE
Enhancement request: Adding notes to a fleet

### ISSUE THREAD

**Issue by Urutsini** [spacedockapp/spacedock#214]
Could you add an entry field to attach a note to a fleet? This would be particularly useful when there is a delay with releases as it would allow noting cards to add that aren't implemented or implemented incorrectly. It would also allow notes to be added regarding play-style and/or tricks with the fleet. (Android)

**Comment by DrNicket** [comment]
Please declare your device version each time you post an issue, just so the developers are clear. Not only does it save time, but the right developer can address it. Thank you.

**Comment by Urutsini** [comment]
I usually do, but I just thought this would be a good addition to all versions of the app.

**Comment by rrgeorge** [comment]
Notes and additional points are already implemented in Mac & iOS.

**Comment by Urutsini** [comment]
My apologies. Will ensure I avoid assumptions and do that in the future. Any chance that enhancements made to the iOS version get added here as requests for the Android version going forward?
