### ISSUE TITLE
Calvin Hudson + Tactical Station + Targeted Phaser Strike cost

### ISSUE THREAD

**Issue by Urutsini** [spacedockapp/spacedock#215]
Not sure if it's just this combo of cards or other slot additions + point reducers, but with Calvin Hudson on S'Gorn + Tactical Station + Targeted Phaser Strike, the Phaser Strike does not have the -1SP cost. (Android)

**Comment by DrNicket** [comment]
It appears to be isolated to Targeted Phaser Strike.
