### ISSUE TITLE
Mac OS version, Error: "Data.xml contains cards..."

### ISSUE THREAD

**Issue by cassiel33** [spacedockapp/spacedock#216]
Everytime on opening Mac OS version of Spacedock I get the following error:

"Data.xml contains cards that have special effects that this version of Space Dock doesn't know how to handle
PlusFiveIfNotKlingon, RomulanHijackers,
OnlyKlingon, Plus4NotPrometheus,
OnlyKlingonCaptainShip"

I've tried:
 * Updated to latest version of app
 * Updated to latest data file
 * Removing Spacedock entirely from my system (including App Support files) and reinstalling

No change.

**Comment by rrgeorge** [comment]
This is not a bug. The app is informing you that there are cards that require special handling that is not yet implemented.
