### ISSUE TITLE
Missing White Maneuvers 

### ISSUE THREAD

**Issue by mathguy6189** [spacedockapp/spacedock#219]
All the white maneuvers are missing from ship movement cards in Version 1.1.26 (107) Mac OS

**Comment by rrgeorge** [comment]
Please provide screenshots. I am not experiencing this issue, so it is likely your app is corrupted somehow. Update to the latest version: 1.1.27 (108) (released just now) to see if that resolves the issue. If not, delete the app and redownload it from spacedockapp.org.
