### ISSUE TITLE
iOS: Reference pages should not use "Detail Disclosure" row accessory type

### ISSUE THREAD

**Issue by HeXetic** [spacedockapp/spacedock#220]
When examining lists of cards or rules independent of squad-building (i.e. selecting anything other than "Squads" at the front page), table rows should not use the "Detail Disclosure" UITableViewCellAccessoryType. This accessory provides both a caret (>) and an info button, with independent tap behaviours.

In the squad-building portion of Space Dock, this accessory type is being used correctly to distinguish between wanting to get info about a thing (tapping the info button) versus actually selecting the thing for this ship/squad/etc. (tapping anywhere else on the row).

In the reference sections, the distinction is not useful. I note that for Ships, Captains, Crew, Talents, Tech, etc. the info-button has been linked to "select row", which results in the info being displayed. However, on the "Reference" page, which contains a selection of STAW rules notes, tapping the info button actually does nothing.

It would be more visually consistent with normal iOS UITableView behaviour if the accessory could be changed depending on if a thing is being selected or just being looked-up. Alternatively, the Reference page should be fixed to behave like the Ships, Captains, Crew, Talents, etc. pages already do.

**Comment by rrgeorge** [comment]
Confirmed.

**Comment by rrgeorge** [comment]
Fixed
