### ISSUE TITLE
Add Feature to Mark Retired Resources

### ISSUE THREAD

**Issue by cassiel33** [spacedockapp/spacedock#222]
Recommend adding a feature to mark retired resources. Maybe in the "View" menu? It could add a strikeout to retired resources' text. Or display them in red text.

This would aid in fleet building for official tournaments.

**Comment by rrgeorge** [comment]
This is already implemented in iOS and Mac.

**Comment by cassiel33** [comment]
Implemented but not yet released? (I've not seen it in iOS or Mac.)

**Comment by rrgeorge** [comment]
On Mac the setting is in Preferences. On iOS the setting is in Space Dock via the Settings app.
