### ISSUE TITLE
Android - Crash

### ISSUE THREAD

**Issue by DrNicket** [spacedockapp/spacedock#225]
When in library under ships with all factions selected, scrolling past Ferengi does not display independents. It crashes consistently.

**Comment by DrNicket** [comment]
I'm on a Nexus 7 Tablet
I believe I'm running v1.1.18 (56)

**Comment by tblackwe** [comment]
Is there a new ship with a different manuver? That has caused this in the
past.

**Comment by rrgeorge** [comment]
The ship class for the Kreechta was spelled incorrectly. I believe this should be resolved, I can confirm later today.

**Comment by rrgeorge** [comment]
Confirmed resolved.
