### ISSUE TITLE
Temporal Wave Front - not in Mirror [Tech] - iOS only

### ISSUE THREAD

**Issue by DrNicket** [spacedockapp/spacedock#227]
Temporal Wave Front is listed in Independent Tech, but not Mirror. 
Confirmed okay in Android, cannot confirm Mac OS.

**Comment by rrgeorge** [comment]
iOS uses the primary faction for section headers in the list view. This upgrade is set correctly as dual faction. Although it displays under the independent header in the list view, it still will filter and not apply penalties for both factions.
