### ISSUE TITLE
Captain Martok (IKS Rotarran) does not reduce Klingon Upgrade costs

### ISSUE THREAD

**Issue by HeXetic** [spacedockapp/spacedock#230]
Captain Martok's card text states that all Klingon Upgrades cost -1SP. However, this points reduction does not seem to work for me in the iOS app. In the attached screenshot, all of the cards on the Maht-H'A are Klingon and none of them has been reduced in points cost. I have double-checked that the Martok is the Martok (4) from the Rotarran.

I am using the latest data from 2015-10-21 and the latest version of the app.

![img_1897](https://cloud.githubusercontent.com/assets/9452039/10641862/0facec14-77e9-11e5-9672-18a13d5e447d.PNG)

**Comment by rrgeorge** [comment]
Martok from the Rotarran is supported in the next app version. It is currently waiting for approval from Apple.
