### ISSUE TITLE
Implement Officers for Android

### ISSUE THREAD

**Issue by tblackwe** [spacedockapp/spacedock#97]
Officers have been spoiled. 
Things to think about
1 resource, 1-4 upgrade slots (Resource costs 3,6,9, or 12 based on number of officers taken. Cost should be linked to the slot on the ship then, much like flagships or fleet captains)
Officer cards are associated with crew, need 1 crew member for ever 1-2 officer cards
They add Crew, Weapon, Tech, and Talent slots.
First officer adds a captain skill

**Comment by rrgeorge** [comment]
Fixed.
